// generated by gen_demo.py -- short waveform demo program
module ROME(
    input [31:0]PC,
    output [31:0] IR
);
reg [31:0] registan [255:0];
initial begin
    registan[ 0]=32'h0AA00093;   // 0x000  x1 = 0x0AA
    registan[ 1]=32'h05500113;   // 0x004  x2 = 0x055
    registan[ 2]=32'h002081B3;   // 0x008  x3 = 0x0FF   add
    registan[ 3]=32'h40208233;   // 0x00C  x4 = 0x055   sub
    registan[ 4]=32'h0020F2B3;   // 0x010  x5 = 0x000   and  (no overlapping bits)
    registan[ 5]=32'h0020E333;   // 0x014  x6 = 0x0FF   or
    registan[ 6]=32'h0020C3B3;   // 0x018  x7 = 0x0FF   xor
    registan[ 7]=32'h12345437;   // 0x01C  x8 = 0x12345000
    registan[ 8]=32'h67840413;   // 0x020  x8 = 0x12345678
    registan[ 9]=32'h00802023;   // 0x024  mem[0] = 0x12345678
    registan[10]=32'h00002483;   // 0x028  x9 = 0x12345678   LW
    registan[11]=32'h00000503;   // 0x02C  x10 = 0x78   LB lane 0
    registan[12]=32'h00100583;   // 0x030  x11 = 0x56   LB lane 1
    registan[13]=32'h00200603;   // 0x034  x12 = 0x34   LB lane 2
    registan[14]=32'h00300683;   // 0x038  x13 = 0x12   LB lane 3
    registan[15]=32'hFFF00713;   // 0x03C  x14 = 0xFFFFFFFF
    registan[16]=32'h00E00223;   // 0x040  byte 4 = 0xFF
    registan[17]=32'h00400783;   // 0x044  x15 = 0xFFFFFFFF   LB  sign-extends
    registan[18]=32'h00404803;   // 0x048  x16 = 0x000000FF   LBU zero-extends
    registan[19]=32'h00E01423;   // 0x04C  half at 8 = 0xFFFF
    registan[20]=32'h00801883;   // 0x050  x17 = 0xFFFFFFFF   LH  sign-extends
    registan[21]=32'h00805903;   // 0x054  x18 = 0x0000FFFF   LHU zero-extends
    registan[22]=32'h00108463;   // 0x058  TAKEN     -> skips the poison below
    registan[23]=32'h66600993;   // 0x05C  POISON    x19 must stay 0
    registan[24]=32'h00109463;   // 0x060  NOT TAKEN -> falls through
    registan[25]=32'h12300A13;   // 0x064  x20 = 0x123   proves fall-through ran
    registan[26]=32'h00800AEF;   // 0x068  x21 = PC+4, jumps over the poison
    registan[27]=32'h66600B13;   // 0x06C  POISON    x22 must stay 0
    registan[28]=32'h77700B93;   // 0x070  x23 = 0x777   landing site
    registan[29]=32'h00000063;   // 0x074  HALT  self-loop
end
assign IR=registan[PC[9:2]];
endmodule
