#!/usr/bin/env python3
"""Short, waveform-friendly demo program. Distinct values, one concept per block.
Writes ROM_demo.sv (drop-in replacement for ROME) and prints a listing."""
from asm import *

P = []
def e(instr, note): P.append((instr, note))

# ---- A: ALU basics.  0xAA and 0x55 are complementary, so the results are obvious
e(addi("x1","x0",0x0AA),  "x1 = 0x0AA")
e(addi("x2","x0",0x055),  "x2 = 0x055")
e(add ("x3","x1","x2"),   "x3 = 0x0FF   add")
e(sub ("x4","x1","x2"),   "x4 = 0x055   sub")
e(and_("x5","x1","x2"),   "x5 = 0x000   and  (no overlapping bits)")
e(or_ ("x6","x1","x2"),   "x6 = 0x0FF   or")
e(xor_("x7","x1","x2"),   "x7 = 0x0FF   xor")

# ---- B: build a recognisable word, store it, read it back
e(lui ("x8",0x12345),     "x8 = 0x12345000")
e(addi("x8","x8",0x678),  "x8 = 0x12345678")
e(sw  ("x8",0,"x0"),      "mem[0] = 0x12345678")
e(lw  ("x9",0,"x0"),      "x9 = 0x12345678   LW")

# ---- C: pull each byte out of that word -- byte-lane selection
e(lb("x10",0,"x0"),       "x10 = 0x78   LB lane 0")
e(lb("x11",1,"x0"),       "x11 = 0x56   LB lane 1")
e(lb("x12",2,"x0"),       "x12 = 0x34   LB lane 2")
e(lb("x13",3,"x0"),       "x13 = 0x12   LB lane 3")

# ---- D: sign vs zero extension -- same address, different answer
e(addi("x14","x0",-1),    "x14 = 0xFFFFFFFF")
e(sb  ("x14",4,"x0"),     "byte 4 = 0xFF")
e(lb  ("x15",4,"x0"),     "x15 = 0xFFFFFFFF   LB  sign-extends")
e(lbu ("x16",4,"x0"),     "x16 = 0x000000FF   LBU zero-extends")

# ---- E: halfword, same idea
e(sh  ("x14",8,"x0"),     "half at 8 = 0xFFFF")
e(lh  ("x17",8,"x0"),     "x17 = 0xFFFFFFFF   LH  sign-extends")
e(lhu ("x18",8,"x0"),     "x18 = 0x0000FFFF   LHU zero-extends")

# ---- F: branch taken, then branch not taken
e(beq ("x1","x1",8),      "TAKEN     -> skips the poison below")
e(addi("x19","x0",0x666), "POISON    x19 must stay 0")
e(bne ("x1","x1",8),      "NOT TAKEN -> falls through")
e(addi("x20","x0",0x123), "x20 = 0x123   proves fall-through ran")

# ---- G: jump and link
e(jal ("x21",8),          "x21 = PC+4, jumps over the poison")
e(addi("x22","x0",0x666), "POISON    x22 must stay 0")
e(addi("x23","x0",0x777), "x23 = 0x777   landing site")

# ---- H: park
e(beq("x0","x0",0),       "HALT  self-loop")

with open("ROM_demo.sv","w") as f:
    f.write("// generated by gen_demo.py -- short waveform demo program\n")
    f.write("module ROME(\n    input [31:0]PC,\n    output [31:0] IR\n);\n")
    f.write("reg [31:0] registan [255:0];\ninitial begin\n")
    for i,(w,note) in enumerate(P):
        f.write(f"    registan[{i:2d}]=32'h{w:08X};   // 0x{i*4:03X}  {note}\n")
    f.write("end\nassign IR=registan[PC[9:2]];\nendmodule\n")

print(f"{len(P)} instructions, halt at 0x{(len(P)-1)*4:X}, retires by ~{25+len(P)*10} ns")
for i,(w,note) in enumerate(P):
    print(f"  0x{i*4:03X}  {w:08X}   {note}")
